---
- hosts: all
  gather_facts: True
  become: yes
  roles:
    - role: base
      #tags:
      #  - base
    - role: zsh
    #  tags: 
    #  - base
    #  - zsh
    #- role: service
    #  tags:
    #    - service
